#!/bin/bash
set -eo pipefail

host="$(hostname --ip-address || echo '127.0.0.1')"

if health="$(curl -fsSL "http://$host:9200/_cat/health?h=status")"; then
    # trim whitespace (otherwise we'll have "red ")
	health="$(echo "$health" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')"
    # single node status is by default yellow, only treat red as a true problem
	if [ "$health" = 'red' ]; then 
        echo >&2 "unexpected health status: $health"
		exit 1
	fi
fi

exit 0